theme: jekyll-theme-merlot

title: South Sea Company

name: Hello
show_downloads: False

description: Hey

footer-links: 
  dribble:
  email:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
