theme: jekyll-theme-merlot

title: South Sea Company

name: By Juan Pedro Crestanello, Maria Jacinta Crestanello, Emanuele Gualandri, & Tancredi Castellano Pucci.
show_downloads: False
forkme_banner: False

description: Hey

footer-links: 
  dribble:
  email:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
