theme: jekyll-theme-merlot

title: Bubbles in the South Sea

name: By Juan Pedro Crestanello, Maria Jacinta Crestanello, Emanuele Gualandri, & Tancredi Castellano Pucci
show_downloads: False
forkme_banner: False

description: By Juan Pedro Crestanello, Maria Jacinta Crestanello, Emanuele Gualandri, & Tancredi Castellano Pucci

footer-links: 
  dribble:
  email:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
